apiVersion: v1
kind: Service
metadata:
  name: test-api-service
  namespace: test-framework
spec:
  type: NodePort
  selector:
    app: test-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30090
